Jolrobles/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('home.urls', 'home'), namespace ='home')),
    path('contenido/', include(('contenido.urls', 'contenido'), namespace='contenido')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contenido/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    path('blog_detail/<int:pk>/', views.BlogDetail.as_view(), name='blog_detail'),

]

home/urls.py
from django.urls import path
from django.conf.urls import url
from home import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path(r'', views.index, name='index'),

]

contenido/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
	image = models.ImageField(upload_to='img/blog')
	titulo = models.CharField(max_length = 100)
	contenido = models.TextField(help_text='Contenido del blog')
	fecha_creacion = models.DateField(null=True)

	class Meta:
		verbose_name = "Blog"
		verbose_name_plural = "Blogs"

	def __str__(self):
		return "%s" %(self.titulo)

class Galeria(models.Model):
	image = models.ImageField(upload_to='img/galeria', null=True)
	titulo = models.CharField(max_length = 100, null=True)
	comentario = models.TextField(help_text='comentario de la foto',null=True)
	fecha_creacion = models.DateField(null=True)

	class Meta:
		verbose_name = "Galeria"
		verbose_name_plural = "Galerias"

	def __str__(self):
		return "%s" %(self.titulo)

class AboutMe(models.Model):
	image = models.ImageField(upload_to='img/about-me', null=True)
	pregunta = models.CharField(max_length=1000)
	respuesta = models.TextField(help_text='respuesta de la pregunta')

	class Meta:
		verbose_name = "About"
		verbose_name_plural = "Abouts"

	def __str__(self):
		return "%s" %(self.pregunta)




class Proyecto(models.Model):
	image = models.ImageField(upload_to='img/proyecto')
	nombre = models.CharField(max_length=100)
	nuevo = models.BooleanField(default=True)
	descripcion = models.TextField(help_text='descripción corta del proyecto')
	url = models.URLField(blank=True, null=True, help_text='Página web del proyecto.')

	class Meta:
		verbose_name = "Proyecto"
		verbose_name_plural = "Proyectos"

	def __str__(self):
		return "%s" %(self.nombre)



class Caracteristica(models.Model):
	caracteristica = models.CharField(max_length = 100)
	proyecto = models.ForeignKey(Proyecto, on_delete=models.CASCADE, related_name='caracteristica_proyecto', null=True)


	class Meta:
		verbose_name = "Caracteristica"
		verbose_name_plural = "Caracteristicas"

		def __str__(self):
			return "%s" %(self.nombre)

home/models.py
from django.db import models


class Portada(models.Model):
	video = models.FileField(upload_to='videos/')

	class Meta:
		verbose_name = "Portada"
		verbose_name_plural = "Portadas"


class Seccion(models.Model):
	icono = models.ImageField(upload_to='img')
	nombre = models.CharField(max_length = 50)
	titulo = models.CharField(max_length = 200)
	subtitulo = models.CharField(max_length = 200)

	class Meta:
		verbose_name = "Seccion"
		verbose_name_plural = "Secciones"

	def __str__(self):
		return "%s" %(self.nombre)

contenido/forms.py
from django import forms
from .models import *

class BlogForm(forms.ModelForm):
	class Meta:
		model = Blog
		fields = '__all__'

contenido/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from .models import *
from .forms import *

class BlogDetail(DetailView):
	model = Blog
	form_class = BlogForm
	# success_url = reverse_lazy('index:suscripcion_list')

home/views.py
from django.shortcuts import render, redirect
from .models import *
from contenido.models import Blog, Galeria, AboutMe, Proyecto

# Create your views here.
def index(request):
	blogs = Blog.objects.all()
	imagenes = Galeria.objects.all()
	about_me = AboutMe.objects.all()
	proyectos = Proyecto.objects.all()
	context = {
		'blogs':blogs,
		'imagenes':imagenes,
		'about_me': about_me,
		'proyectos': proyectos,

	}
	return render(request, 'index.html', context)

# Carga de landing page presentacion
def landing_page(request):
    configuracion = Configuracion.objects.first()
    titulo = configuracion.titulo_landing_page
    descripcion = configuracion.descripcion_landing_page
    texto_testimonios = configuracion.texto_testimonios
    texto_nuestros_clientes = configuracion.texto_nuestros_clientes
    secciones = Seccion.objects.all()
    testimonios = Testimonio.objects.all()
    context = {
        'titulo':titulo,
        'descripcion':descripcion,
        'texto_testimonios':texto_testimonios,
        'texto_nuestros_clientes':texto_nuestros_clientes,
        'secciones':secciones,
        'testimonios':testimonios,
    }
    return render(request, 'landing_page/index.html', context)

templates/base.html
<!DOCTYPE html>
<!--INDEX DE LANDING PAGE-->
<html lang="es">
{% load staticfiles %}
{% load bootstrap4 %}
{% block header %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}  {% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-style.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
</head>
{% endblock header %}

<body>
  {% block content %}


  {% endblock content %}
   	{% block contact_us %}
    <footer>
      <p>
        Sigueme
        <i><a href="https://www.facebook.com/jolrobless/"><i class="fa fa-facebook"></i></a></i>
        <i><a href="#"><i class="fa fa-twitter"></i></a></i>
        <i><a href="#"><i class="fa fa-linkedin"></i></a></i>
        <i><a href="#"><i class="fa fa-rss"></i></a></i>
        <i><a href="#"><i class="fa fa-behance"></i></a></i>
        <br>
        Copyright &copy; 2019 JYSYS

      | Diseñado por <a href="https://www.facebook.com/jysysloja" target="_parent"><em>Jysys</em></a>
    </p>
    </footer>

   	{% endblock contact_us %}

	{% block scripts %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>

    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
	{% endblock scripts %}
  </body>
</html>

templates/contenido/blog.html
{% load staticfiles %}
<script>
	// Columna ID en orden descendente
	$(document).ready(function() {
	    $('#datatable').DataTable( {
	        "order": [[ 1, "desc" ]]
	    } );
	} );
</script>
<div class="clearfix"></div>
  <div class="cd-full-width first-slide">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="content first-content" id="datatable">
            {% for blog in blogs %}
              <h4>{{blog.titulo}}</h4>
              <p>{{blog.contenido}}</p>
              <div class="primary-button">
                <a href="{% url 'contenido:blog_detail' blog.pk %}">Ver más</a>
              </div>
              <br>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</li>

templates/contenido/blog_detail.html
{% extends "base.html" %}

{% block title %} Jolrobless {% endblock title %}
{% load staticfiles %}
{% load bootstrap4 %}
{% block content %}

    <div class="overlay"></div>
    <section class="top-part">
      <img src="{{ object.image.url }}">
    Your browser does not support the image tag.
    </section>


  <section class="cd-hero">

    <ul class="cd-hero-slider">
      <li class="selected">
        <div class="heading">
          <h1>{{object.titulo}}</h1>
          <span>Bienvenido</span>
        </div>
        <div class="cd-half-width second-slide">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="content second-content">
                  <div class="row"><br>
                    <div class="col-md-4">
                    </div>
                    <div class="col-md-4">
                      <img src="{{ object.image.url }}">
                    </div>
                  </div>
                  <div class="row">
                      <div class="col-md-12">
                        <div class="text">
                          <h4>{{object.titulo}}</h4>
                          <p>{{object.fecha_creacion}}</p>
                          <p>{{object.contenido}}</p>
                          <div class="primary-button">
                            <a href="/">Volver</a>
                          </div><br>
                        </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>

  </section> <!-- .cd-hero -->
{% endblock content %}

templates/contenido/galeria.html
{% load staticfiles %}
<div class="cd-half-width fourth-slide">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="content fourth-content">
          <div class="row">
            {% for imagen in imagenes %}
            <div class="col-md-3 project-item">
              <a href="{{ object.image.url }}" data-lightbox="image-1"><img src="{{ object.image.url }}"></a>
            </div>
            {% endfor %}
            <div class="col-md-3 project-item">
              <a href="{% static 'img/item-02.jpg' %}" data-lightbox="image-1"><img src="{% static 'img/project-item-02.jpg' %}"></a>
            </div>
            <div class="col-md-3 project-item">
              <a href="{% static 'img/item-03.jpg' %}" data-lightbox="image-1"><img src="{% static 'img/project-item-03.jpg' %}"></a>
            </div>
            <div class="col-md-3 project-item">
              <a href="{% static 'img/item-04.jpg' %}" data-lightbox="image-1"><img src="{% static 'img/project-item-04.jpg' %}"></a>
            </div>
            <div class="col-md-3 project-item">
              <a href="{% static 'img/item-05.jpg' %}" data-lightbox="image-1"><img src="{% static 'img/project-item-05.jpg' %}"></a>
            </div>
            <div class="col-md-3 project-item">
              <a href="{% static 'img/item-06.jpg' %}" data-lightbox="image-1"><img src="{% static 'img/project-item-06.jpg' %}"></a>
            </div>
            <div class="col-md-3 project-item">
              <a href="{% static 'img/item-07.jpg' %}" data-lightbox="image-1"><img src="{% static 'img/project-item-07.jpg' %}"></a>
            </div>
            <div class="col-md-3 project-item">
              <a href="{% static 'img/item-08.jpg' %}" data-lightbox="image-1"><img src="{% static 'img/project-item-08.jpg' %}"></a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/index.html
{% extends "base.html" %}

{% block title %} Jolrobless {% endblock title %}
{% load staticfiles %}
{% block content %}

    <div class="overlay"></div>
    <section class="top-part">
    <video controls autoplay loop>
      <source src="{% static 'videos/video.mp4' %}" type="video/mp4">
      <source src="{% static 'videos/video.ogg' %}" type="video/ogg">
    Your browser does not support the video tag.
    </video>
    </section>


  <section class="cd-hero">
    {% block nav_bar %}
    {% include "nav_bar.html" %}
  {% endblock nav_bar %}

    <ul class="cd-hero-slider">

      <li class="selected">
        <div class="heading">
          <h1>Nuevos Post publicados</h1>
          <span>Bienvenido</span>
        </div>

        {% block blog %}
  		{% include "contenido/blog.html" %}
    	{% endblock blog %}

      <li>
        <div class="heading">
          <h1>Sobre mi</h1>
          <span>Bienvenido</span>
        </div>
        <div class="cd-half-width second-slide">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="content second-content"><br>
                  {% for pregunta in about_me %}
                  <div class="row">
                    <div class="first title-content">
                      <h4>{{pregunta.pregunta}}</h4>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-5 left-image">
                      <img src="{{pregunta.image.url}}">
                    </div><br>
                    <div class="col-md-7">
                      <div class="right-about-text">
                        <h4></h4>
                        <p>{{pregunta.respuesta}}</p>
                      </div>
                    </div>
                  </div><br>
                  {% endfor %}
                  <div class="primary-button">
                    <a href="#">Hoja de vida</a>
                  </div><br>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>

      <li>
        <div class="heading">
          <h1>Trabajos personales</h1>
          <span>Bienvenido</span>
        </div>
        <div class="cd-half-width third-slide">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="content third-content">
                  {% for proyecto in proyectos %}
                  <div class="row">
                    <div class="col-md-7 left-image">
                      <img src="{{proyecto.image.url}}">
                    </div>
                    <div class="col-md-5">
                      <div class="right-feature-text">
                        <h4>{{proyecto.nombre}}<br>
                          {% if proyecto.nuevo == True %}
                            <em>Nuevo</em>
                          {% else %}
                            <em></em>
                          {% endif %}
                        </h4>
                        <p>{{proyecto.descripcion}}</p>

                        <div class="feature-list">
                          <ul>
                            {% for caracteristica in proyecto.caracteristica_proyecto.all %}
                            <p>- {{caracteristica.caracteristica}}</p>
                            {% endfor %}
                          </ul>
                        </div>
                        <div class="primary-button">
                          <a href="{{proyecto.url}}">Visítalo</a>
                        </div>
                      </div>
                    </div>
                  </div>
                  {% endfor %}
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>

      <li>
        <div class="heading">
          <h1>Fotos personales interesantes</h1>
          <span>Bienvenidos</span>
        </div>
        <div class="cd-half-width fourth-slide">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="content fourth-content">
                  <div class="row">
                    {% for imagen in imagenes %}
                    <div class="col-md-3 project-item">
                      <a href="{{ imagen.image.url }}" data-lightbox="image-1"><img src="{{ imagen.image.url }} " width="50" height="210"></a>
                    </div>
                    {% endfor %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>


      </li>

      <li>
        <div class="heading">
          <h1>Comunicate conmigo</h1>
          <span>Bienvenido</span>
        </div>
        <div class="cd-half-width fivth-slide">
          <div class="container">
            <div class="row">
              <div class="col-md-12">
                <div class="content fivth-content">
                  <div class="row">
                    <div class="col-md-4">
                      <div class="left-info">
                        <p>Maecenas imperdiet sagittis lacus, ut consequat velit iaculis id. Praesent eu consequat urna. Morbi justo dolor, ornare sed lorem et, auctor iaculis ligula.
                        <br><br>
                        <em>3344 Donec mollis libero<br>at metus luctus 10110</em>
                        </p>
                        <ul class="social-icons">
                          <i><a href="#"><i class="fa fa-facebook"></i></a></i>
                          <i><a href="#"><i class="fa fa-twitter"></i></a></i>
                          <i><a href="#"><i class="fa fa-linkedin"></i></a></i>
                          <i><a href="#"><i class="fa fa-rss"></i></a></i>
                          <i><a href="#"><i class="fa fa-behance"></i></a></i>
                        </ul>
                      </div>
                    </div>
                    <div class="col-md-8">
                      <div class="row">
                        <form id="contact" action="" method="post">
                          <div class="col-md-6">
                            <fieldset>
                              <input name="name" type="text" class="form-control" id="name" placeholder="Your Name" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-6">
                            <fieldset>
                              <input name="email" type="email" class="form-control" id="email" placeholder="Email" required="">
                            </fieldset>
                          </div>
                          <div class="col-md-12">
                            <fieldset>
                              <textarea name="message" rows="6" class="form-control" id="message" placeholder="Message" required=""></textarea>
                            </fieldset>
                          </div>
                          <div class="col-md-12">
                            <fieldset>
                              <button type="submit" id="form-submit" class="btn">Send Message</button>
                            </fieldset>
                          </div>
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </li>
    </ul> <!-- .cd-hero-slider -->
  </section> <!-- .cd-hero -->
{% endblock content %}

templates/nav_bar.html
{% load staticfiles %}
<div class="cd-slider-nav">
  <nav>
    <span class="cd-marker item-1"></span>
    <ul>
      <li class="selected"><a href="#0"><div class="image-icon"><img src="{% static 'img/home-icon.png' %}"></div><h6>Inicio</h6></a></li>
      <li><a href="#0"><div class="image-icon"><img src="{% static 'img/about-icon.png' %}"></div><h6>Sobre Mi</h6></a></li>
      <li><a href="#0"><div class="image-icon"><img src="{% static 'img/featured-icon.png' %}"></div><h6>Proyectos</h6></a></li>
      <li><a href="#0"><div class="image-icon"><img src="{% static 'img/projects-icon.png' %}"></div><h6>Galeria</h6></a></li>
      <li><a href="#0"><div class="image-icon"><img src="{% static 'img/contact-icon.png' %}"></div><h6>Contactame</h6></a></li>
    </ul>
  </nav>
</div> <!-- .cd-slider-nav -->